/line_follower:
  ros__parameters:
    waypoints: [0.00, 0.00, 0.00, 5.00, 0.00, 0.00]
    k_p: 1.0

/naive_line_follower:
  ros__parameters:
    waypoints: [0.00, 0.00, 0.00, 5.00, 0.00, 0.00]
    k_p: 1.0