/line_follower:
  ros__parameters:
    waypoints: [0.00, 1.00, 0.00, 5.00, 1.00, 0.00]
    k_p: 1.0
    k_d: 20.0

/naive_line_follower:
  ros__parameters:
    waypoints: [0.00, 1.00, 0.00, 5.00, 1.00, 0.00]
    k_p: 1.0
    k_d: 20.0